say ( locale_quest ( 10107 ) ) 
if select ( locale_quest ( 10065 ) , locale_quest ( 10066 ) ) == 1 then 
if ship_defense_mgr . is_running ( ) then 
say ( locale_quest ( 10111 ) ) 
return 
end 
local pids = { party . get_member_pids ( ) } 
local noQuestMembers = { } 
local notEnoughLevelMembers = { } 
local noTicketMembers = { } 
local questCheck = true 
local ticketCheck = true 
local levelCheck = true 
local ticketGroup = { get_special_item_group ( 10033 ) } 
if ship_defense_mgr . need_party ( ) then 
if not party . is_party ( ) then 
syschat ( locale_quest ( 10099 ) ) 
return 
end 
if not party . is_leader ( ) then 
say ( locale_quest ( 10100 ) ) 
return 
end 
for i , pid in next , pids , nil begin 
q . begin_other_pc_block ( pid ) 
if not ship_defense . main_quest_complete ( ) then 
table . insert ( noQuestMembers , pc . get_name ( ) ) 
questCheck = false 
end 
if pc . get_level ( ) < 90 then 
table . insert ( notEnoughLevelMembers , pc . get_name ( ) ) 
levelCheck = false 
end 
if ship_defense_mgr . need_ticket ( ) then 
local hasTicket = false 
for idx = 1 , table . getn ( ticketGroup ) , 2 begin 
if pc . count_item ( ticketGroup [ idx ] ) >= ticketGroup [ idx + 1 ] then 
hasTicket = true 
break 
end 
end 
if not hasTicket then 
table . insert ( noTicketMembers , pc . get_name ( ) ) 
ticketCheck = false 
end 
end 
q . end_other_pc_block ( ) 
end 
if not questCheck then 
say ( locale_quest ( 10101 ) ) 
for i , name in next , noQuestMembers , nil begin 
say ( color ( 1 , 1 , 0 ) , " " .. name ) 
end 
if not levelCheck then 
wait ( ) 
else 
return 
end 
end 
if not levelCheck then 
say ( locale_quest ( 10102 ) ) 
for i , name in next , notEnoughLevelMembers , nil begin 
say ( color ( 1 , 1 , 0 ) , " " .. name ) 
end 
if not ticketCheck then 
wait ( ) 
else 
return 
end 
end 
if ship_defense_mgr . need_ticket ( ) then 
if not ticketCheck then 
say ( locale_quest ( 10103 ) ) 
for i , name in next , noTicketMembers , nil begin 
say ( color ( 1 , 1 , 0 ) , " " .. name ) 
end 
return 
end 
end 
if party . get_near_count ( ) < table . getn ( pids ) then 
say ( locale_quest ( 10110 ) ) 
return 
end 
if ship_defense_mgr . need_ticket ( ) then 
for i , pid in next , pids , nil begin 
q . begin_other_pc_block ( pid ) 
for i = 1 , table . getn ( ticketGroup ) , 2 begin 
if pc . count_item ( ticketGroup [ i ] ) >= ticketGroup [ i + 1 ] then 
pc . remove_item ( ticketGroup [ i ] , ticketGroup [ i + 1 ] ) 
break 
end 
end 
q . end_other_pc_block ( ) 
end 
end 
else 
if ship_defense_mgr . need_ticket ( ) then 
local hasTicket = false 
for idx = 1 , table . getn ( ticketGroup ) , 2 begin 
if pc . count_item ( ticketGroup [ idx ] ) >= ticketGroup [ idx + 1 ] then 
hasTicket = true 
break 
end 
end 
if not hasTicket then 
table . insert ( noTicketMembers , pc . get_name ( ) ) 
ticketCheck = false 
end 
if not ticketCheck then 
say ( locale_quest ( 10103 ) ) 
for i , name in next , noTicketMembers , nil begin 
say ( color ( 1 , 1 , 0 ) , " " .. name ) 
end 
return 
end 
for i = 1 , table . getn ( ticketGroup ) , 2 begin 
if pc . count_item ( ticketGroup [ i ] ) >= ticketGroup [ i + 1 ] then 
pc . remove_item ( ticketGroup [ i ] , ticketGroup [ i + 1 ] ) 
break 
end 
end 
end 
end 
say ( locale_quest ( 10098 ) ) 
ship_defense_mgr . start ( ) 
end 
