add_ox_quiz(1, "메틴2의 제작사는 이미르이다.", true)
add_ox_quiz(1, "신수국의 깃발 색은 파란색이다", false)
add_ox_quiz(1, "천조국의 깃발 색은 빨간색이다", false)
add_ox_quiz(1, "진노국의 깃발 색은 노란색이다", false)
add_ox_quiz(1, "메틴의 경험치를 나타내는 동그라미는 각각 25%을 차지한다", true)
add_ox_quiz(1, "고급말의 먹이는 당근이다.", false)
add_ox_quiz(1, "결혼은 25레벨 이상 남,녀 캐릭터가 커플링과 예복이 있어야 된다", true)
add_ox_quiz(1, "신수국의 2차 마을은 영안읍성 이다", true)
add_ox_quiz(1, "4대 스탯은 체력 근력 마력 지력이다", false)
add_ox_quiz(1, "무사의 최고 투구는 북성투구이다", false)
add_ox_quiz(1, "수라의 최고 투구는 애희투구이다", false)
add_ox_quiz(1, "자객의 최고 갑옷은 비영이다.", false)
add_ox_quiz(1, "자객이 입는 갑옷중 흰색 갑옷의 이름은 살풍이다.", true)
add_ox_quiz(1, "선악수치가 5224인 캐릭터는 영웅이다", false)
add_ox_quiz(1, "여왕벌은 5년이상 살 수 있다", true)
add_ox_quiz(1, "물고기도 기침을 한다.", true)
add_ox_quiz(1, "열대어가 입을 맞추는 것은 애정의 표현이다.", false)
add_ox_quiz(1, "고래는 쉼 5M 이하의 물 속에서 잠을 잔다.", false)
add_ox_quiz(1, "코끼리 상아는 당구공의 재료로 쓰이기도 했다.", true)
add_ox_quiz(1, "뒤로 날 수 있는 새도 있다.", true)
add_ox_quiz(1, "염소는 낮과 저녁의 눈동자 모양이 다르다.", true)
add_ox_quiz(1, "한국 돌고래와 미국 돌고래는 말이 통한다.", false)
add_ox_quiz(1, "소에게는 윗니가 전부 있다.", false)
add_ox_quiz(1, "늑대는 개, 호랑이는 고양이, 닭은 꿩과에 속한다.", true)
add_ox_quiz(1, "원숭이에게도 지문이 있다.", true)
add_ox_quiz(1, "병아리도 배꼽이 있다.", true)
add_ox_quiz(1, "거미는 원래 수중생활을 했었다.", true)
add_ox_quiz(1, "게의 다리는 모두 10개이다.", true)
add_ox_quiz(1, "용은 장수를 상징하는 십장생중 하나이다.", false)
add_ox_quiz(1, "체온이 일정한 동물을 변온동물이라고 한다. ", false)
add_ox_quiz(1, "식충식물인 [파라지옥]은 파리만 잡는다.", false)
add_ox_quiz(1, "이구아나는 머리를 문지르면 최면에 빠진다.", true)
add_ox_quiz(1, "북극곰은 겨울잠을 자는 동물이다 ", false)
add_ox_quiz(1, "칠면조는 머리부분을 7가지 색깔로 바꿀 수 있다 ", false)
add_ox_quiz(1, "수컷나귀와 암말사이에서 태어난 것이 노새이다. ", true)
add_ox_quiz(1, "북한산은 북한에 있다 ", false)
add_ox_quiz(1, "god 맴버중 안데니의 이름은 본명이다 ", false)
add_ox_quiz(1, "멀리 바라볼 수 있도록 높이 만들어 놓은 대를 전망대라 한다.", true)
add_ox_quiz(1, "회덮밥은 일본에서도 있다 ", false)
add_ox_quiz(1, "신문 동아일보에서는 광수생각이 나온다 ", false)
add_ox_quiz(1, "세계 전자상거래 행사는 전자상거래 관련 세계적인 행사이다", true)
add_ox_quiz(1, "2차세계대전에서 가장 늦게 항복한 국가는 독일이다", false)
add_ox_quiz(1, "인체에 신장은 콩팥이라고도 한다", true)
add_ox_quiz(1, "딸기는 장미과에 속한다.", true)
add_ox_quiz(1, "아라비아숫자1부터100사이에는9라는 숫자가모두19개 들어있다.", false)
add_ox_quiz(1, "고추 1관은 5Kg 이다.", false)
add_ox_quiz(1, "<링>의 원작은 프랑스 영화이다.", false)
add_ox_quiz(1, "인간의 뇌 세포는 재생이 안 되는 신체세포이다.", true)
add_ox_quiz(1, "우리나라최초의 대중가요는1923년부터 불리워진 [희망가]이다.", false)
add_ox_quiz(1, "사람의 세포는 개미의 세포보다 크다.", false)
add_ox_quiz(1, "우리나라에서 가장 넓은 차선은 광화문 앞에 16차선이다.", true)
add_ox_quiz(1, "위가 없어도 사람은 살 수 있다.", true)
add_ox_quiz(1, "사람의 땀은 산성이다.", true)
add_ox_quiz(1, "일간신문은 3종 우편물이다.", true)
add_ox_quiz(1, "파란 전등 밑에서 빨강 종이를 보면 보라색으로 보인다.", false)
add_ox_quiz(1, "빵은 순수한 우리말이다.", true)
add_ox_quiz(1, "차례 상을 차릴 때 흰 과일은 동쪽, 붉은 과일은 서쪽에 놓는다.", false)
add_ox_quiz(1, "버스가 급정거하면 몸이 앞으로 쏠린다.", true)
add_ox_quiz(1, "태양빛을 쬐면 피부가 검게타는데 그원인이 되는 것은 자외선이다.", true)
add_ox_quiz(1, "도리지꽃은 별을 닮았다.", true)
add_ox_quiz(1, "가을 하늘 공활한데로 시작하는 것은 애국가 3절이다.", true)
add_ox_quiz(1, "소프라노는 음역이 높고, 알토는 음역이 낮다.", true)
add_ox_quiz(1, "오늘 다음은 내일, 내일 다음은 모레, 모레 다음은 글피이다.", true)
add_ox_quiz(1, "우리나라 호수 중 가장 깊은 호수는 천지이다.", true)
add_ox_quiz(1, "사람의 손가락과 발가락의 합은 절대 20개이다.", false)
add_ox_quiz(1, "결혼식에서 신부가 손에 드는 꽃다발을 [부케]라고 한다.", true)
add_ox_quiz(1, "술이나 차로 먹거나 향이 좋아 천연방향제로 쓰이는 것은 모과다.", true)
add_ox_quiz(1, "국방의 의무는 국민의 3대 의무 중 하나이다.", true)
add_ox_quiz(1, "가제트, 존 맥클레인의 공통적인 직업은 형사이다.", true)
add_ox_quiz(1, "건빵엔 세개의 구멍이 있다.", false)
add_ox_quiz(1, "거문고의 줄은 7줄이다.", false)
add_ox_quiz(1, "국회의원의 임기는 4년이다.", true)
add_ox_quiz(1, "형법상 성년자의 나이는 만 14세 이상이다.", true)
add_ox_quiz(1, "밤에 라면을 먹고 자면 다음날 얼굴이 붓는다.", true)
add_ox_quiz(1, "정상제품인 바둑알은 흰 돌과 검은 돌의 크기가 다르다.", true)
add_ox_quiz(1, "배설과 배출은 다른 것이다.", true)
add_ox_quiz(1, "교육제도 중, 우리나라의 의무교육은 중학교 까지이다.", true)
add_ox_quiz(1, "밀물과 썰물은 하루에 2번씩 일어난다.", true)
add_ox_quiz(1, "버스전용차로의 표시는 '빨간색'으로 한다.", false)
add_ox_quiz(1, "비누를 전자레인지에 넣고 돌리면 팝콘처럼 부풀어 오른다.", true)
add_ox_quiz(1, "경운기도 운전면허를 따야 운전 할 수 있다.", false)
add_ox_quiz(1, "지문은 사람에게만 있다.", false)
add_ox_quiz(1, "한국의 초고속 인터넷 가입자 수는 당당히 세계 1위이다.", false)
add_ox_quiz(1, "일본말로 '사랑합니다'는 아이시떼루이다.", true)
add_ox_quiz(1, "최초로 달에 착륙한 우주선은 아폴로 11호이다.", false)
add_ox_quiz(1, "하루에 머리카락이 100개정도 빠지면 심각한 탈모증이다.", false)
add_ox_quiz(1, "실로폰은 타악기이다.", true)
add_ox_quiz(1, "사람의 키는 아침과 저녁이 2Cm까지 차이가 날 수 있다.", true)
add_ox_quiz(1, "우리나라 기차 중 일반석의 요금이 가장 비싼 기차는 새마을호이다.", true)
add_ox_quiz(1, "비누는 센물에 잘 안녹는다.", true)
add_ox_quiz(1, "피리는 사물놀이에 쓰이는 악기 중 하나이다.", false)
add_ox_quiz(1, "사람의 갈비뼈는 총 14쌍이다.", false)
add_ox_quiz(1, "개인도 국보를 소유할 수 있다.", true)
add_ox_quiz(1, "우리나라의 명절은 양력이다.", false)
add_ox_quiz(1, "비행기출발시간이란 비행기의 탑승문이 완전히 닫힌순간을 말한다.", false)
add_ox_quiz(1, "애니메이션은 한 장,한 장의 그림으로 만들어낸다. ", true)
add_ox_quiz(1, "지구가 1년에 한번 도는것을 '공전'이라 한다.", true)
add_ox_quiz(1, "웨딩드레스는 고유어이다.", false)
add_ox_quiz(1, "음악의 빠르기를 나타내는 용어 중 가장 느린 것은 라르고이다.", true)
add_ox_quiz(1, "성경책은 모두 500장이다.", false)
add_ox_quiz(1, "경주에는 불국사가 있고 불국사에는 다보탑이 있다.", true)
add_ox_quiz(1, "색맹도 색깔이 있는 꿈을 꿀 수가 있다.", false)
add_ox_quiz(1, "긴급전화번호 중 115는 전기고장을 신고하는 전화번호다.", false)
add_ox_quiz(1, "과학 용구에 쓰이는 삼발이는 말 그대로 발이 3개가 있다.", true)
add_ox_quiz(1, "백설공주에 나오는 일곱 난쟁이의 직업은 광부였다.", true)
add_ox_quiz(1, "버스의 무임승차 나이는 6세 미만이다.", true)
add_ox_quiz(1, "거시기는 사투리이다.", false)
add_ox_quiz(1, "식용유가 끓어 화재가 났을  경우 물을 뿌려야햔다. ", false)
add_ox_quiz(1, "장미의 색상 중 자연적으로 생긴 초록색이 있다. ", false)
add_ox_quiz(1, "독도에 우편번호가 있다.", true)
add_ox_quiz(1, "높은 산에서 밥이 설익는 이유는 끓는 온도가 높아지기 때문이다. ", false)
add_ox_quiz(1, "미국에는 스님이 없다", false)
add_ox_quiz(1, "지구가 처음 생겨났을 때는 뜨거워서 생명체가 살 수 없었다.", true)
add_ox_quiz(1, "미국, 한국, 중국, 일본중 티콕에 속하지 않는 나라는 일본이다.", false)
add_ox_quiz(1, "베토벤은 모짜르트보다 더 오래 살았다.", true)
add_ox_quiz(1, "우리나라의 민주화 운동이 일어난 곳은 광주이다. ", true)
add_ox_quiz(1, "고려의 유생 김부식이 쓴 삼국시대의 역사책은 [삼국유사]다.", false)
add_ox_quiz(1, "이순신 장군은 학익진으로 이긴 적이 있다.", true)
add_ox_quiz(1, "런던과 서울은 반나절(12시간)의 시차가 있다.", false)
add_ox_quiz(1, "사이판은 크레타 섬 옆에 있는 관광휴양지이다.", false)
add_ox_quiz(1, "모나리자는 미켈란젤로의 작품이다. ", false)
add_ox_quiz(1, "로댕의 생각하는 사람은 오른손으로 턱을 받치고 있다.", true)
add_ox_quiz(1, "고구려를 세운 왕은 태조 왕건이다.", false)
add_ox_quiz(1, "허준이 만든 의학책 이름은 동의보감이다. ", true)
add_ox_quiz(1, "너 자신을 알라 라는 말을 한 사람은 소크라테스이다.", true)
add_ox_quiz(1, "라면의 종주국은 러시아이다. ", false)
add_ox_quiz(1, "중국의 만리장성의 실제 길이는 10000(만)리 이다.", false)
add_ox_quiz(1, "북한의 공식적인 명칭은 조선공산주의인민공화국이다.", false)
add_ox_quiz(1, "북한에도 복권이 있다.", true)
add_ox_quiz(1, "북한에서 뮤지컬을 [가무 이야기]라고 한다.", true)
add_ox_quiz(1, "화장실은 북한말로 위생장이다.", false)
add_ox_quiz(1, "<사계>는 모짜르트의 작품이다.", false)
add_ox_quiz(1, "구석기인은 주로 구릉,산간에서 생활하였다. ", false)
add_ox_quiz(1, "셰익스피어의 희곡 햄릿의 주인공인 햄릿은 네델란드 사람이다.", false)
add_ox_quiz(1, "충무공의 3대첩은 한산도대첩,명랑대첩,진주대첩이다. ", false)
add_ox_quiz(1, "이집트의 수도는 튀니스이다. ", false)
add_ox_quiz(1, "이순신 장군은 1592년 한산도 대첩에서 전사하였다.", false)
add_ox_quiz(1, "미국의 수도는 세계 최대의 도시 뉴욕이다. ", false)
add_ox_quiz(1, "머리를 감는다는 뜻의 북한말은 머리를 빤다이다.", true)
add_ox_quiz(1, "유럽 러시아와 시베리아쪽 러시아는 우랄 산맥을 기준으로 나뉜다", true)
add_ox_quiz(1, "러시아 아랄해 근방국가 중 흑토가 나는 나라는 우즈베키스탄이다", false)
add_ox_quiz(1, "석유의 생산이 가장 많은 나라는 사우디아라비아이다.", true)
add_ox_quiz(1, "남부 유럽은 관광산업으로 돈을 벌어서 산다", true)
add_ox_quiz(1, "서남아시아와 북부아프리카에서 유대교인 국가는 이스라엘이다", true)
add_ox_quiz(1, "걸프 전쟁이 일어난 해는 1991년이다", true)
add_ox_quiz(1, "OPEC의 뜻은 섬유 수출국 기구이다", false)
add_ox_quiz(1, "페르시아만에는 세계전체매장량의 약 75%의 석유가 매장되어있다", true)
add_ox_quiz(1, "라인 강 유역에서는 이집트 문명이 발달하였다", false)
add_ox_quiz(1, "월드컵 제 1회 대회는 스위스에서 열렸다", false)
add_ox_quiz(1, "월드컵에서 이탈리아가 세번째 우승을 대회는 제 11회 월드컵이다", false)
add_ox_quiz(1, "제1회 WBC대회는 미국에서 개최되었다", true)
add_ox_quiz(1, "제1회 WBC대회는 한국은 4강에 진출했다", true)
add_ox_quiz(1, "프로레슬링 선수 언더테이커의 동생은 케인이다 ", true)
add_ox_quiz(1, "프로레슬링은 아마추어 레슬링과 규칙이 전혀 틀리다 ", true)
add_ox_quiz(1, "프로레슬링 선수 스톤콜드는 천사라는 호칭을 듣고있다", false)
add_ox_quiz(1, "레슬링은 시간제한이 있다.", true)
add_ox_quiz(1, "2002년 월드컵에서 한국은 4강에 진출했다", true)
add_ox_quiz(1, "World Cup 축구 대회는 4년마다 개최된다.", true)
add_ox_quiz(1, "동방신기의 멤버는 6명이다.", false)
add_ox_quiz(1, "릴리프란 야구에서의 구원투수를 말한다.", true)
add_ox_quiz(1, "체조에서 안마 종목은 남자만이 할 수 있다. ", true)
add_ox_quiz(1, "해리포터와 비밀의 방에서 나오는 뱀의 이름은 바실리스크 뱀이다.", true)
add_ox_quiz(1, "근대 올림픽의 창시자 쿠베르탱은 프랑스 사람이다.", true)
add_ox_quiz(1, "쇼트트랙에서 스케이트날 부분이 결승선에 닿아야 완주로인정된다.", true)
add_ox_quiz(1, "김동성이 오노의 반칙에 금메달을 뺏긴것은 나가노 올림픽때이다.", false)
add_ox_quiz(1, "최지우의 본명은 최미자이다.", false)
add_ox_quiz(1, "2000년 프로야구 우승팀은 두산베어스이다 ", false)
add_ox_quiz(2, "현재 최고의 공격력을 가진 무기는 무쌍검이다", false)
add_ox_quiz(2, "활 중에서 황룡대궁은 방패가 있어 방어력이 높아진다.", false)
add_ox_quiz(2, "웅귀 족장의 레벨은 50이다", true)
add_ox_quiz(2, "자객은 단검류와 활류만 착용이 가능하다.", false)
add_ox_quiz(2, "암마석은 레벨 40이다", false)
add_ox_quiz(2, "망각비전서로 마스터 이전 스킬 1 포인트를 차감할 수 있다", false)
add_ox_quiz(2, "대왕몬스터 중 서한산에 있는 대왕 몬스터는 구미호이다", true)
add_ox_quiz(2, "하선동의 장군몬스터는 돌원숭이이다", true)
add_ox_quiz(2, "영석중 흑마영석의 성능은 물리공격 회피이다", false)
add_ox_quiz(2, "영석 실패시에는 생성된 깨어진석은 개량을 통해 제거할 수 있다.", true)
add_ox_quiz(2, "사귀탑 5층을 돌파하기 위해서는 가짜 메틴석을 찾아야 한다.", false)
add_ox_quiz(2, "질주하는 말 위에서 적을 흩어지게 하는 승마스킬은 철마난무이다.", true)
add_ox_quiz(2, "구운물고기 중 즉시 생명력회복500을 올려주는 물고기는 백련이다.", true)
add_ox_quiz(2, "물고기에서 얻은 조개를 열면 백진주, 청진주, 흑진주등이 나온다", false)
add_ox_quiz(2, "결혼식은 전용맵으로 이동한 뒤 주례NPC를 통해 승인된다.", true)
add_ox_quiz(2, "이혼은 마을 광장 경비병을 통해 가능하다.", true)
add_ox_quiz(2, "결혼할 배우자와 레벨차이가 25이상 나지 않아야 한다.", false)
add_ox_quiz(2, "아리영은 보험금을 노리고 남편을 살해했다는 루머가 있다.", true)
add_ox_quiz(2, "파티시 설정기능 중 어태커는 파티원의 공격력을 상승시킨다", true)
add_ox_quiz(2, "파티시 설정기능 중 탱커는 파티원의 최대체력을 상승시킨다", true)
add_ox_quiz(2, "파티시 설정기능 중 버서커는 파티원의 공격속도를 하락시킨다", false)
add_ox_quiz(2, "파티시 설정기능 중 디펜더는 파티원의 마법방어력을 상승시킨다", false)
add_ox_quiz(2, "나한군은 삼연참이라는 스킬을 가지고 있다.", true)
add_ox_quiz(2, "별기군은 검풍이라는 스킬을 가지고 있다.", true)
add_ox_quiz(2, "비살군은 독기궁이라는 스킬을 가지고 있다.", false)
add_ox_quiz(2, "무당의 최고 갑옷은 붕신의이다.", false)
add_ox_quiz(2, "수라만의 무기는 퇴마도와 실미도이다.", false)
add_ox_quiz(2, "오줌이 배출될때 [부르르]떨리는 것은 수분이 빠져나갔기 때문이다 ", false)
add_ox_quiz(2, "벼룩은 암컷과 수컷가운데 수컷의 몸집이 더 크다.", false)
add_ox_quiz(2, "사슴의 뿔은 매년 빠졌다. 다시 난다.", true)
add_ox_quiz(2, "느림보 개미핥기는 혀를 1분에 120번 넘게 날름거린다.", true)
add_ox_quiz(2, "[물고기가 수면위로 호흡한다]라는 말은 비가 올 징조다. ", true)
add_ox_quiz(2, "개구리는 배를 문지르면 잠이든다. ", true)
add_ox_quiz(2, "뱀은 유리 위를 기어가지 못한다.", true)
add_ox_quiz(2, "고래는 물속의 바위에 몸을 끼우고 잔다 ", false)
add_ox_quiz(2, "땅 속에서 여름잠을 자는 물고기가 있다", true)
add_ox_quiz(2, "하마의 땀은 사람과는 달리 붉은 색이다.", true)
add_ox_quiz(2, "바퀴벌레는 약 시속 150Km의 속력으로 이동한다.", true)
add_ox_quiz(2, "카멜레온은 눈가리개를 하면 몸의 색깔을 바꿀 수 없다.", true)
add_ox_quiz(2, "다이너마이트는 니트로 셀룰로우스란 물질로 만든것이다", false)
add_ox_quiz(2, "일진회는 친일단체이다.", true)
add_ox_quiz(2, "북한의 나라꽃은 진달래이다 ", false)
add_ox_quiz(2, "눈은 빛을 받게 되면 홍채는 커지고 동공은 작아진다.", true)
add_ox_quiz(2, "비행기의 블랙박스는 검은색이다.", false)
add_ox_quiz(2, "단군신화가 기록된 문헌은 삼국유사이다.", true)
add_ox_quiz(2, "남극에도 우편번호가 있다.", false)
add_ox_quiz(2, "헌법상 비준의 권한을 가진 사람은 국회의장이다.", false)
add_ox_quiz(2, "지구에서 육안으로 볼 수 있는 별의 숫자는 약 4,000개 정도이다.", false)
add_ox_quiz(2, "기온의 일교차가 가장 심한 곳은 극지방이다.", false)
add_ox_quiz(2, "크리스탈유리는 납성분이 포함되어 있다.", true)
add_ox_quiz(2, "꺼벙이란 꿩의 새끼를 말한다.", true)
add_ox_quiz(2, "색소폰은 그 이름이 최초의 연주자 이름으로 부터 유래된 것이다.", true)
add_ox_quiz(2, "북쪽을 가리키는 별은 북극성, 남쪽을 가리키는 별은 남십자성이다.", true)
add_ox_quiz(2, "왕대비는 왕의 증조할머니를 의미한다.", false)
add_ox_quiz(2, "모범택시는 대중교통수단에서 제외된다.", true)
add_ox_quiz(2, "온대와 열대의 중간 기후대를 아열대라 한다.", true)
add_ox_quiz(2, "빈혈은 출혈에 의해서만 생긴다.", false)
add_ox_quiz(2, "남자와 여자의 목소리 중 멀리 들리는 것은 여자의 목소리이다.", true)
add_ox_quiz(2, "발렌타인데이카드는 가장 축하카드 소비량이 많은 날이다.", false)
add_ox_quiz(2, "눈의 수정체가 혼탁해지는 질환은 백내장이다.", true)
add_ox_quiz(2, "열대지방에 자라는 나무에는 나이테가 없다.", true)
add_ox_quiz(2, "겨울철 우리나라 날씨의 특징을 가장 잘 나타낸 말은 삼한사온이다.", true)
add_ox_quiz(2, "경제활동인구에는 실업자가 포함된다.", true)
add_ox_quiz(2, "국립현충원은 경찰관도 잠들어 있다. ", true)
add_ox_quiz(2, "화이트데이는 본래 명칭이 머쉬멜로우데이였다.", true)
add_ox_quiz(2, "여의도 국회의사당을 둘러 쌰고 있는 돌기둥의 수는 모두 24개이다.", true)
add_ox_quiz(2, "우리나라에서 최초로 지정된 국립 공원은 지리산이다.", true)
add_ox_quiz(2, "도돌이표가 있는 마디는 두번 되풀이해서 연주한다.", true)
add_ox_quiz(2, "감사합니다는 순우리말이다. ", false)
add_ox_quiz(2, "산성비는 황산화물이나 인산화물등 대기오염물질로 인해서 내린다.", true)
add_ox_quiz(2, "대한민국의 3번째 대통령은 노무현대통령이다. ", false)
add_ox_quiz(2, "현 대통령의 임기기간은 4년이다.", false)
add_ox_quiz(2, "사법고시에 합격해 판사가 되면 1급 공무원 대우를 받는다.", false)
add_ox_quiz(2, "사리는 국수 등 면을 감은 뭉치 단위다.", true)
add_ox_quiz(2, "거시기는 전라도 사투리이다. ", false)
add_ox_quiz(2, "경남진주에서는 언니를 응가라고 부른다.", true)
add_ox_quiz(2, "식물의 발아조건은 햇빛이다. ", false)
add_ox_quiz(2, "조선시대 호패는 16세 이상 모든 남녀가 소지했다.", false)
add_ox_quiz(2, "미주알고주알에서 미주알은 우리 몸의 창자 끝부분을 말한다.", true)
add_ox_quiz(2, "영어사전에는 zzz라는 단어가 있다.", true)
add_ox_quiz(2, "환상풍의 자유로운기악을 세레나데라고 한다.", false)
add_ox_quiz(2, "설날에 웃어른을 찾아 세배를 하고 다니는 사람을 세배꾼이라 한다.", true)
add_ox_quiz(2, "설날아침에 입는 새 옷을 설빔이라고 한다.", true)
add_ox_quiz(2, "[활용]이라는 말의 올바른 발음은 [활룡]이다.", false)
add_ox_quiz(2, "사람의 5가지 감각중 가장 먼저 나빠지는 것은 청각이다.", false)
add_ox_quiz(2, "우리나라 남해안은 리아스식 해안이다.", true)
add_ox_quiz(2, "몽골계 인종은 모두 몽고반점이 있다.", true)
add_ox_quiz(2, "북어 한 쾌는 30마리이다.", true)
add_ox_quiz(2, "생산의 3요소는 자연, 노동, 자본이다.", true)
add_ox_quiz(2, "조카는 촌수로 따지면 4촌관계이다. ", false)
add_ox_quiz(2, "다섯 손톱가운데 가장 잘 자라는 손톱은 엄지손톱이다.", false)
add_ox_quiz(2, "덴마크의 3대 명물로는 튤립, 풍차, 나막신 이다.", true)
add_ox_quiz(2, "결혼전 신부집으로 예물을 보내는 절차를 폐백이라 한다.", false)
add_ox_quiz(2, "별자리는 봄과 여름이 다르다.", true)
add_ox_quiz(2, "인공위성을 최초로 쏘아올린 나라는 미국이다.", false)
add_ox_quiz(2, "현재, 서울지하철은 일본의 도쿄지하철보다 연장길이가 길다.", false)
add_ox_quiz(2, "주민등록증에 있는 위조방지 홀로그램은 무궁화 모양이다.", false)
add_ox_quiz(2, "북한의 여성들도 쌍커풀 수술을 한다 ", true)
add_ox_quiz(2, "호그와트 마법학교 교장선생님인 덤블도어는 [땅벌]이라는 뜻이다 ", true)
add_ox_quiz(2, "우리나라에서 선거권이 인정되는 연령은 18세이다.", false)
add_ox_quiz(2, "산소운반에 중요한 열할을 하는 것은 '백혈구'이다.", false)
add_ox_quiz(2, "호떡이란 뜻은 오랑캐가 전쟁시에 먹는 식량에서 유래되었다", true)
add_ox_quiz(2, "라면의 면은 국물보다 10배나 지방이 많다.", false)
add_ox_quiz(2, "그리스 신화에서 아테네는 '사랑'의 신이다.", false)
add_ox_quiz(2, "성경에 나와있는 최초의 이름은 이브였다 ", false)
add_ox_quiz(2, "신문의 특종기사란 다른 경쟁지에 보도 안 된 기사이다", true)
add_ox_quiz(2, "북두칠성은 시계의 반대 방향으로 회전한다.", true)
add_ox_quiz(2, "태어날 때부터 가지고 태어난 성질을 선천성이라 한다", true)
add_ox_quiz(2, "TVA는 매스컴과 관계 있다.", false)
add_ox_quiz(2, "안네의 일기가 나온 배경은 1차세계대전이다", false)
add_ox_quiz(2, "포스트잇의 끈끈이는 망친본드를 사용한 것 이다", true)
add_ox_quiz(2, "제일 높은 산과 제일 깊은 바다를 비교해 보면 산이 더 높다. ", false)
add_ox_quiz(2, "사마귀 있는 사람과 키스를 하면 자신도 사마귀가 생긴다.", true)
add_ox_quiz(2, "포도에 묻은 하얀 가루는 효모이다", true)
add_ox_quiz(2, "지구가 태양을 한바퀴 도는 데는 정확하게 365일 6시간 걸린다", true)
add_ox_quiz(2, "은하는 우유를 뜻하는 그리스어에서 나왔다.", true)
add_ox_quiz(2, "피가 몸을 완전히 한바퀴 도는 데에는 46초가 걸린다. ", true)
add_ox_quiz(2, "최초의 우주 비행 생물체는 개이다.", true)
add_ox_quiz(2, "손톱은 뼈가 아니고 피부가 변해서 된 것이다.", true)
add_ox_quiz(2, "드라이아이스를 만지면 화상에 걸린다. ", true)
add_ox_quiz(2, "하와에게 선악과를 먹어보라고 권한 것은 도마뱀이다", false)
add_ox_quiz(2, "한국축구 월드컵의 첫 골 주인공은 박창선 선수이다", true)
add_ox_quiz(2, "축구에서 펠레 스코어란 2:1을 말한다.", false)
add_ox_quiz(2, "이번 WBC에서 이승엽 선수가 친 홈런의 개수는 5개 이다.", true)
add_ox_quiz(2, "국가대표축구팀 새유니폼의 등번호판에 새겨진한글은 투혼이다.", true)
add_ox_quiz(2, "<레옹>에서 장르노와 게리 올드만은 마지막에 함께 죽는다. ", true)
add_ox_quiz(2, "근대 5종목 경기에는 사격, 수영이 포함된다. ", true)
add_ox_quiz(2, "제 20회 토리노 동계올림픽에서 우리나라는 종합순위 7위에 올랐다.", true)
add_ox_quiz(2, "2002년 월드컵에서 박지성은 스위스를 상대로 결승골을 뽑았다", false)
add_ox_quiz(2, "한국은  양궁과 스피드스케이팅 강국이다.", false)
add_ox_quiz(2, "이승엽, 이종범, 박찬호선수는 제1회 WBC MVP로 선정되었다", true)
add_ox_quiz(2, "역사상 한 여인이 가장 많은 아이를 낳은 출산기록이 60명 이하다.", false)
add_ox_quiz(2, "세계에서 가장 큰 꽃은 라플레시아다.", true)
add_ox_quiz(2, "홍차의 최대 소비국은 중국이다.", false)
add_ox_quiz(2, "라니냐란 에스파냐 어로 남자아이라는 뜻이다.", false)
add_ox_quiz(2, "왕건은 삼국을 통일했다.", false)
add_ox_quiz(2, "이순신은 1545년에 태어났다", true)
add_ox_quiz(2, "세계에서 제일 처음으로 텔레비전을 방송한 나라는 영국이다.", true)
add_ox_quiz(2, "우리나라 국보 중에서 가장 오랜된 석탑은 불국사의 다보탑이다.", false)
add_ox_quiz(2, "강원도 강릉시에 있는 이율곡 생가의 호칭은 오죽헌이다.", true)
add_ox_quiz(2, "신사임당은 1504년에 강릉 북평촌에서 원균의 둘째 딸로 출생했다.", false)
add_ox_quiz(2, "황성신문에 시일야방성대곡이란 사설을 기고한 사람은 정인보이다.", false)
add_ox_quiz(2, "이순신은 일본이 침략해 왔을 때 강강술래를 지시했다.", true)
add_ox_quiz(2, "보사노바는 멕시코 음악이다.", false)
add_ox_quiz(2, "나이팅게일이 활약한 전쟁은 크림전쟁이다.", true)
add_ox_quiz(2, "멸균을 북한에서는 [균 깡그리 죽이기] 라 한다. ", true)
add_ox_quiz(2, "소크라테스는 결혼을 했다.", true)
add_ox_quiz(2, "홍루몽은 중국의 4대 기서이다. ", false)
add_ox_quiz(2, "고대 문명 중 세계 최초의 문명은 이집트 문명이다. ", true)
add_ox_quiz(2, "홍콩이 영국 영토가 된 조약은 베이징 조약이다.", false)
add_ox_quiz(2, "인도차이나 반도에서  지배를 받지 않은 나라는 미얀마이다.", false)
add_ox_quiz(2, "노르웨이에서 사는 바이킹들을 노르만 족이라 부른다.", true)
add_ox_quiz(2, "유럽에서 아시아 계의 사람들이 사는 곳은 헝가리와 핀란드이다", true)
add_ox_quiz(2, "남부 유럽의 기후는 지중해성 기후이다", true)
add_ox_quiz(2, "3권분립은 미국독립선언의 내용이다.", false)
add_ox_quiz(2, "프랑스의 통화명칭은 실링이다.", false)
add_ox_quiz(2, "우리 나라가 대수로공사를 해 준 나라는 알제리이다", false)
add_ox_quiz(2, "서남 아시아에서는 방목을 한다", false)
add_ox_quiz(2, "동부 아시아에서는 혼합 농업을 한다", false)
add_ox_quiz(3, "신수국은 상인들이 모여서 건설한 국가이다", true)
add_ox_quiz(3, "대륙에서 정통성을 주장하고 있는 군사대국은 천조국이다.", false)
add_ox_quiz(3, "신수국의 세번째 마을이며 길드마을인 마을의 이름은 와룡현이다.", false)
add_ox_quiz(3, "PVP시 선악 수치가 -9780 이면 악인이다.", false)
add_ox_quiz(3, "살아있는 물고기는 합칠 수 있으나, 죽은 물고기는 합칠 수 없다.", false)
add_ox_quiz(3, "철갑기마대를 이끌고 최초의 통일 국가를 이룩한 사람은 이석이다.", false)
add_ox_quiz(3, "아리영은 떡을 팔아 연명하는 마을 주민이다", true)
add_ox_quiz(3, "태우랑은 유화랑과 연인사이이다.", false)
add_ox_quiz(3, "덕배는 나무꾼이지만 곡괭이를 팔아 돈을 벌어 드리고 있다", true)
add_ox_quiz(3, "대련장으로 가기 위해서는 유랑을 통해 대련 신청을 하여야 한다", false)
add_ox_quiz(3, "행상인은 예복과 특이 아이템을 판매한다.", false)
add_ox_quiz(3, "무기에 박을 수 있는 영석의 종류는 8개이다.", true)
add_ox_quiz(3, "방어구에 박을 수 있는 영석의 종류는 6개 이다.", true)
add_ox_quiz(3, "활을 사용할 수 있는 케릭터는 자객과 무당이다.", false)
add_ox_quiz(3, "문어는 조개를 껍질 째 먹고 껍질만 버린다 ", false)
add_ox_quiz(3, "강한독을 가진 개구리 1마리의독은 사람을 2천명 이상 죽일수있다.", true)
add_ox_quiz(3, "바다에 사는 상어는 부레가 없다 ", true)
add_ox_quiz(3, "낙타의 등에는 많은 양의 물이 들어있다 ", false)
add_ox_quiz(3, "강아지에게 초콜릿을 먹이는 것은 위험하다 ", true)
add_ox_quiz(3, "우리나라 김장철 김치에 쓰이는 무와 배추는 십자화과에 속한다.", true)
add_ox_quiz(3, "기업간의 인재를 스타우트 해주는 사람들을 헤드헌터라고 한다.", true)
add_ox_quiz(3, "한자의 음과 훈을 빌어 우리말을 적던 표기법은 한글이다.", false)
add_ox_quiz(3, "음악 CD의 사이에 끼어있는 종이를 Booklet(부클릿)이라고 한다.", true)
add_ox_quiz(3, "남사당 놀이에는 6마당 중 버나란 땅재주를 말한다.", false)
add_ox_quiz(3, "블랙박스는 비행기의 꼬리 부분에 둔다.", true)
add_ox_quiz(3, "궁중어로 임금의 붕어는 임금의 혼례를 뜻한다.", false)
add_ox_quiz(3, "흥부가는 판소리 여섯마당에 속하지 않는다.", false)
add_ox_quiz(3, "반고리관은 소리를 듣는 데 필요한 기관이다. ", false)
add_ox_quiz(3, "1024 메가바이트를 나타내는 말은 1 킬로바이트이다. ", false)
add_ox_quiz(3, "법적으로 유언의 효력이 있는 최소 연령은 17세이다.", true)
add_ox_quiz(3, "많은 사람이 한꺼번에 들고 일어남을 뜻하는 한자는 봉기이다.", true)
add_ox_quiz(3, "동요 학교종의 작사, 작곡한 사람의 이름은 김메리이다.", true)
add_ox_quiz(3, "그리니치 표준시라는 뜻의 약자는 GMT이다. ", true)
add_ox_quiz(3, "기업의 인수와 합병라는 뜻의 약자는 M&A이다.", true)
add_ox_quiz(3, "섭씨는 스웨덴의 천문학자인 셀시우스가 정한 온도의 단위이다.", true)
add_ox_quiz(3, "윤선도의 오우가중 다섯 벗이란 물, 돌, 소나무, 대나무 , 해 이다.", false)
add_ox_quiz(3, "오라토리오는 대부분 성서의 내용을 다루고 있다.", true)
add_ox_quiz(3, "반 알렌대란 방사선대를 말한다.", true)
add_ox_quiz(3, "오케스트라 합주는 바이올린 수가 가장 많다. ", true)
add_ox_quiz(3, "양파에는 휘발성 물질이 있다. ", true)
add_ox_quiz(3, "동식물들의 화석이 주로 발견되는 암석은 화강암이다. ", false)
add_ox_quiz(3, "기업의 인수와 합병을 뜻하는 경제용어를 'B2B'라고 한다.", false)
add_ox_quiz(3, "금성에 최초로 연착륙한 인공 우주선은 금성 4호이다. ", false)
add_ox_quiz(3, "피망은 북한말로 사자고추다. ", true)
add_ox_quiz(3, "남도 민요에 까투리 타령은 속하지 않는다. ", false)
add_ox_quiz(3, "식초를 넣으면 부글부글 거리는 것은 탄산수소나트륨이다. ", true)
add_ox_quiz(3, "우유가 상했는지 확인하려면 냉수에 몇 방울을 떨어뜨려보면 된다.", true)
add_ox_quiz(3, "맨틀은 젤리같은 성질의 물질이다.", true)
add_ox_quiz(3, "서양인의 장은 동양인의 장보다 길다.", false)
add_ox_quiz(3, "세종로에 있는 이순신 장군 동상은 칼을 오른손에 쥐고 있다.", true)
add_ox_quiz(3, "세계에서 평균 수명이 가장 긴 나라는 일본이다.", true)
add_ox_quiz(3, "죽다의 속된 말인 골로 가다에서 골은 고택골을 뜻한다.", true)
add_ox_quiz(3, "영어로 It’s muggy 는 후덥지근해라는 뜻이다.", true)
add_ox_quiz(3, "구세군은 선교와 사회봉사 활동을 주로 하는 기독교의 한 교파이다. ", false)
add_ox_quiz(3, "X-mas란 표현은 예수를 부정하기 위해 X표시를한데서 시작됐다.", false)
add_ox_quiz(3, "A4용지의 규격은 황금비율인 1.618 : 1에 맞춰져 있다.", false)
add_ox_quiz(3, "한해의 마지막 때를 우리말로 세모라고 한다.", false)
add_ox_quiz(3, "티눈은 어린이에게 더 잘 생기는 병이다 ", false)
add_ox_quiz(3, "체중이 무거운 사람이 티눈이 걸릴 확률이 높다", true)
add_ox_quiz(3, "우리나라 최초의 라면값은 10원이었다", true)
add_ox_quiz(3, "모라토리움이란 통화계혁이다.", false)
add_ox_quiz(3, "라면 한개의 전체 면발의 길이는 50~60m이다 ", true)
add_ox_quiz(3, "피카소는 레오나르도 다빈치보다 먼저 태어났다 ", false)
add_ox_quiz(3, "몹시두려워하여 벌벌떨면서 조심한다는 한자성어는 전전반측이다", false)
add_ox_quiz(3, "웰빙은 Well living의 준말이다", false)
add_ox_quiz(3, "미술품 중 세계 최고가의 기록을 가진 화가는 피카소다. ", false)
add_ox_quiz(3, "전 세계 사람들이 가장 많이 가지고 있는 혈액형은  A형이다.", false)
add_ox_quiz(3, "아브라함의 원래 이름은 아브라였다.", false)
add_ox_quiz(3, "2003년은 UN이 정한 [세계 물의 해]이다", true)
add_ox_quiz(3, "산성비는 ph.5.6 이하를 말한다. ", true)
add_ox_quiz(3, "처음으로 월드컵에서 골을 넣은 선수는 김주성 선수이다 ", false)
add_ox_quiz(3, "월드컵 축구는 국제축구연맹에서 주최하는 세계축구선수대회이다. ", true)
add_ox_quiz(3, "최우수선수를 가리키는 MVP는 Most Valuable Player의 약자이다.", true)
add_ox_quiz(3, "2006 토리노 동계올림픽대회의 마스코트는 물과불을 상징한다", false)
add_ox_quiz(3, "제1회 WBC대회에서 이승엽선수는 6개의 홈런을 쳤다", false)
add_ox_quiz(3, "토리노동계올림픽에서 한국은 금메달 4개를 획득했다", false)
add_ox_quiz(3, "토리노동계올림픽에서 한국은 쇼트트랙에서만 메달을 획득했다", false)
add_ox_quiz(3, "2002년 월드컵 조별예선에서 한국은 2승 1패를 했다", false)
add_ox_quiz(3, "봅슬레이 영화 쿨러닝의 배경이 된 국가는 남아프리카 공화국이다", false)
add_ox_quiz(3, "1997년 스코틀랜드에서 복제된 복제양의 이름은 둘리이다.", false)
add_ox_quiz(3, "아카펠라란 악기 반주가 없이 연주하는 것으로 르네상스의 종교곡이다.", true)
add_ox_quiz(3, "[북대서양조약기구]라는 뜻의 외래어 약자는 [NATO]이다.", true)
add_ox_quiz(3, "제로섬 사회의 저자는 네이스 비트이다. ", false)
add_ox_quiz(3, "그린피스(Green Peace)란 [국제환경보호단체]를 말한다.", true)
add_ox_quiz(3, "조선과 가장 늦게 근대적 통상조약을 맺은 국가는 영국이다.", false)
add_ox_quiz(3, "SDI는 미국의 우주전략방위계획이다.", true)
add_ox_quiz(3, "3.1운동은 올해 87주년을 맞이하였다.", true)
add_ox_quiz(3, "인터폴(Interpol)이란 국제형사경찰기구이다.", true)
add_ox_quiz(3, "우리나라가 IMF에 돈을 다 갚은 것은 2001년이다.", true)
add_ox_quiz(3, "그리스와 터키 사이에 있는 바다는 에게해이다.", true)
add_ox_quiz(3, "금병매는 중국 4대 기서 중 하나이다.", true)
add_ox_quiz(3, "우리나라 최초의 주식회사는 1899년에 설립된 한일은행이다.", false)
add_ox_quiz(3, "우리나라 4대 국경일은 광복절, 개천절, 제헌절, 삼일절이다.", true)
add_ox_quiz(3, "대한민국 법에서 형법상 가장 큰 죄는 여적(與敵)죄 다.", true)
add_ox_quiz(3, "라벨의 <볼레로>는 오페라이다. ", false)
add_ox_quiz(3, "유희왕에서 유희는 오시리시의 청공용을 갖고 있다. ", true)
add_ox_quiz(3, "사람의 고기를 먹는 미노타우로스를 죽인것은 헤라클레스이다.", true)
add_ox_quiz(3, "걸리버여행기는 작자 미상의 작품이다. ", false)
add_ox_quiz(3, "에디슨은 노벨상을 받지않았다. ", true)
add_ox_quiz(3, "오딧세우스는 트로이 전쟁과 관련이 있는 인물이다. ", true)
add_ox_quiz(3, "부산 동삼동의 이른민무늬토기는 구석시 시대의 유적이다. ", false)
add_ox_quiz(3, "강화도조약은 조선이 일본과 맺은 최초의 근대적 조약이다. ", true)
add_ox_quiz(3, "우리가 명필가로 잘알고 있는 한석봉은 본명이다. ", false)
add_ox_quiz(3, "독립 미국의 첫 수도였던 도시는 필라델피아이다.", true)
add_ox_quiz(3, "폴란드의 수도는 바르샤바이다.", true)
add_ox_quiz(3, "베를린 영화제의 최우수작품상은 황금곰상이다.", true)
add_ox_quiz(3, "스위스 남부해안의 바닷물은 다른 지역보다 염분이 높다.", false)
add_ox_quiz(3, "대통령은 헌법개정안에 대하여 거부권을 행사할 수 없다. ", true)
add_ox_quiz(3, "북서부 유럽에서 3개국어를 쓰는 나라는 룩셈부르크와 스위스이다.", true)
add_ox_quiz(3, "아메리카를 앵글로와 라틴으로 나누는 경계는 파나마 지협이다", false)
add_ox_quiz(3, "싱가포르는 남부 아시아에서 가장 잘 사는 곳이다", false)
add_ox_quiz(3, "사막화 현상이 계속되고 있는 곳을 부르는 말은 사헬 지대이다", true)
