add_ox_quiz(1,"騎馬的任務是從NPC老海盜處領取嗎？",false)
add_ox_quiz(1,"雜貨店老闆的老爸是武器店老闆嗎？",false)
add_ox_quiz(1,"蓮嫂的老公是王鐵匠嗎？",false)
add_ox_quiz(1,"劉嫂的老公是書蟲嗎？",false)
add_ox_quiz(1,"梁柏年是書蟲的弟子嗎？",false)
add_ox_quiz(1,"將查看名稱設定成一直，可一直顯示玩家名稱嗎？",false)
add_ox_quiz(1," +6寒風劍升級到+7只需要《魚骨X1》對嗎？",false)
add_ox_quiz(1,"《合成高手指南》需要《永恆鑄件》和《玄鐵》,對嗎？",false)
add_ox_quiz(1,"《小虹的哥哥》任務最終獎勵為經驗60W,五加皮X10對嗎？",false)
add_ox_quiz(1,"37級任務要求擊殺的《秘宗劍客》是在《昇龍谷》出現嗎？",false)
add_ox_quiz(1,"2級任務,只能選擇擊殺幼狼10只對嗎？",false)
add_ox_quiz(1,"3級任務,可以選【幼狼】25只或者是【灰狼】10只對嗎?",false)
add_ox_quiz(1,"4級任務,完成後所得到獎勵為【護身環牌＋1】，對嗎？",false)
add_ox_quiz(1,"幫助梁柏年收集桃花的任務，是收集25個嗎?",false)
add_ox_quiz(1,"今天非得扒你的皮不可!是【黑風左護法】的臺詞嗎?",false)
add_ox_quiz(1,"猛將說自己曾被手持倚天劍的神女追的滿街跑，對嗎？",false)
add_ox_quiz(1,"龍駒online截圖,是保存到遊戲用戶端檔夾裏嗎?",false)
add_ox_quiz(1,"按住〈Shift〉鍵不放會顯示所有人物和物品的名稱嗎？",false)
add_ox_quiz(1,"組隊中隊伍成員最多是9人嗎？",false)
add_ox_quiz(1,"組隊經驗分配的模式任何人都可以設定嗎？",false)
add_ox_quiz(1,"組隊經驗分配的模式只有本隊中的成員可以設定嗎？",false)
add_ox_quiz(1,"右鍵點擊馬匹選擇上馬選項,可以騎馬，對嗎？",false)
add_ox_quiz(1,"大家打起精神來,這樣怎嗎行?是鬼族哨兵的臺詞嗎?",false)
add_ox_quiz(1,"跟我打,可別想活著回去!是鬼族將軍的臺詞嗎?",false)
add_ox_quiz(1,"一輩子在戰場上,我也不後悔是鬼族法師的臺詞嗎?",false)
add_ox_quiz(1,"這次的毒可不能再失敗了…是鬼族屠刀的臺詞嗎?",false)
add_ox_quiz(1,"幫助梁柏年收集柿子花的任務，是收集6個嗎?",false)
add_ox_quiz(1,"傳送點在地圖上的標識是淡黃色三角形嗎？",false)
add_ox_quiz(1,"傳送點在地圖上的標識是淡綠色淩形嗎？",false)
add_ox_quiz(1,"傳送點在地圖上的標識是淡紅色橢圓形嗎？",false)
add_ox_quiz(1,"人物屬性中,智力影響最大精力值和物理防禦力嗎？",false)
add_ox_quiz(1,"龍駒online中有四個國家可以供玩家選擇。",false)
add_ox_quiz(1,"人物屬性中,增加力量只影響魔法攻擊力嗎？",false)
add_ox_quiz(1,"龍駒online是美國《ymir》公司研發的嗎？",false)
add_ox_quiz(1,"一個帳號在同一伺服器可以同時選擇兩個國家的人物嗎？",false)
add_ox_quiz(1,"一個帳號上最多能建立4個角色嗎？",false)
add_ox_quiz(1,"猛將說自己看到了5級稱號為獄帝的修羅，猛將說的對嗎？",false)
add_ox_quiz(1,"10級以下角色死亡，選擇任何復活都幾率損失經驗嗎？",false)
add_ox_quiz(1,"角色1級時就可以找城內的NPC加入門派學習技能嗎？",false)
add_ox_quiz(1,"獲得技能點後,按B鍵打開技能視窗後,可以修練技能對嗎？",false)
add_ox_quiz(1,"目前遊戲中的設定，武器和裝備最高可到加10，對嗎？",false)
add_ox_quiz(1," 有本事和我單挑.是黑風斬頭目怪的臺詞嗎?",false)
add_ox_quiz(1,"斷月波是劍宗猛將的技能之一嗎？",false)
add_ox_quiz(1,"跳斬是劍宗猛將的技能之一嗎？",false)
add_ox_quiz(1,"震撼、獅吼、戰魂都是氣宗猛將的技能嗎？",false)
add_ox_quiz(1,"劍氣、劍氣沖宵、劍風都是氣宗猛將的技能嗎？",false)
add_ox_quiz(1,"報名參加國戰的是找戰魂嗎？",false)
add_ox_quiz(1,"遊戲中結婚男方要求25級以上，女方要求23級以上嗎？",false)
add_ox_quiz(1,"天藍石、紫鴉石、漆石、月光石、都可鑲嵌到盔甲上嗎？",false)
add_ox_quiz(1,"炭金、水晶、孔雀石、琥珀、都可鑲嵌到武器上嗎？",false)
add_ox_quiz(1,"碎靈指、劍魔、魂靈都是幻舞的技能嗎？",false)
add_ox_quiz(1,"束縛、魔靈、噬體都是黑魔的技能嗎？",false)
add_ox_quiz(1,"佩帶熱情的面具後,做接吻的動作不需要對方同意,對嗎？",false)
add_ox_quiz(1,"佩帶熱情的面具後,做擁抱的動作不需要對方同意,對嗎？",false)
add_ox_quiz(1,"佩帶熱情的面具後,做打耳光動作不需要對方同意,對嗎？",false)
add_ox_quiz(1,"佩帶熱情的面具後,做接吻的動作同性之間也可以,對嗎？",false)
add_ox_quiz(1,"佩帶熱情的面具後,做擁抱的動作同性之間也可以,對嗎？",false)
add_ox_quiz(1,"遊戲中NPC小強的姐姐是圓圓嗎？",false)
add_ox_quiz(1,"<製作武器>任務中，需要的布條是從雜貨店老闆處領取嗎？",false)
add_ox_quiz(1,"遊戲中騎乘馬匹是右鍵點擊你的馬嗎？",false)
add_ox_quiz(1,"遊戲中下馬是左鍵點擊你的馬嗎？",false)
add_ox_quiz(1,"做鼓掌表情動作時，不需要佩帶熱情的面具，對嗎？",false)
add_ox_quiz(1,"做歡呼表情動作時，不需要佩帶熱情的面具，對嗎？",false)
add_ox_quiz(1,"做招手表情動作時，需要佩帶熱情的面具，對嗎？",false)
add_ox_quiz(1,"製作1瓶桃花液需要十朵桃花嗎？",false)
add_ox_quiz(1,"1朵柿子花可以製作出10瓶柿子花液嗎？",false)
add_ox_quiz(1,"58級任務<與情報員會員>，觸發任務的NPC是戰魂嗎？",false)
add_ox_quiz(1,"55級任務,古代書籍之最後的書籍,任務觸發人是書蟲嗎？",false)
add_ox_quiz(1,"51級任務：鑲嵌青瓷的秘密，任務觸發人是伯樂嗎？",false)
add_ox_quiz(1,"古代書籍之舒寒山的痕跡任務,任務觸發人是警備隊長嗎？",false)
add_ox_quiz(1,"古代書籍之調查沙漠的裁決者,任務觸發人是警備隊長嗎？",false)
add_ox_quiz(1,"古代書籍調查密宗寺院,任務觸發人是警備隊長嗎？",false)
add_ox_quiz(1,"38級任務,關於書蟲,任務觸發人是書蟲的老婆蓮嫂嗎？",false)
add_ox_quiz(1,"任務,尋找【戰魂】是2級的任務嗎？",false)
add_ox_quiz(1,"任務,尋找【雜貨店】是2級的任務嗎？",false)
add_ox_quiz(1,"任務,第一次訓練 是1級的任務嗎？",false)
add_ox_quiz(1,"NPC圓圓一直想嫁的人是年輕商人嗎？",false)
add_ox_quiz(1,"遊戲中單方面離婚必須交出兩個定情信物對嗎？",false)
add_ox_quiz(1,"幫會成員投資遊戲幣可以提升幫會等級嗎？",false)
add_ox_quiz(1,"在幫會戰中可以使用超級記憶卷對嗎？",false)
add_ox_quiz(1,"向拒絕的幫會申請幫會戰，在三小時以內也可以，對嗎？",false)
add_ox_quiz(1,"34級人物可以騎乘成年馬，對嗎？",false)
add_ox_quiz(1,"45級人物可以騎乘良駒，對嗎？",false)
add_ox_quiz(1,"馬匹體力耗盡死亡時，使用乾草可以復活，對嗎？",false)
add_ox_quiz(1,"玩家常說的紅國是指天調國嗎？",false)
add_ox_quiz(1,"玩家常說的藍國是指新受國嗎？",false)
add_ox_quiz(1,"玩家常說的黃國是指進勞國嗎？",false)
add_ox_quiz(1,"人物稱號為殺手時，稱號顏色是紅色，對嗎？",false)
add_ox_quiz(1,"人物稱號為霸王時，稱號顏色是深紅色，對嗎？",false)
add_ox_quiz(1,"人物稱號為獄帝時，稱號顏色為深藍色，對嗎？",false)
add_ox_quiz(1,"人物稱號為平民時，稱號顏色是綠色，對嗎？",false)
add_ox_quiz(1,"人稱稱號為俠客時，稱號顏色為白色，對嗎？",false)
add_ox_quiz(1,"人物稱號為英雄時，稱號顏色為淡藍色，對嗎？",false)
add_ox_quiz(1,"神女可以學習的技能凝神是狂雷門的嗎？",false)
add_ox_quiz(1,"龍駒online的開發商是韓國暴雪公司嗎？",false)
add_ox_quiz(1,"龍駒online中NPC元斌是男性，對嗎？",false)
add_ox_quiz(1,"神女可以學習的技能飄仙是潛龍門的嗎？",false)
add_ox_quiz(1,"刺客可以學習的技能魅影是鋒刀門的嗎？",false)
add_ox_quiz(1,"修羅可以學習的技能龍卷波是幻舞門的嗎？",false)
add_ox_quiz(1,"修羅可以學習的技能靈魔、劍魔、旋魔均為幻舞門的嗎？",false)
add_ox_quiz(1,"龍駒online中的等級任務都有時間限制嗎？",false)
add_ox_quiz(1,"找到空間移動術師可以直接到其他國家的主城，對嗎？",false)
add_ox_quiz(1,"找空間移動術師移動到雪寒山需要15000兩，對嗎？",false)
add_ox_quiz(1,"猛將可以加入的門派是劍宗和鋒刀，對嗎？",false)
add_ox_quiz(1,"刺客可以加入的門派是百羿和狂雷嗎？",false)
add_ox_quiz(1,"吸寶石卷:是使用後可以將永恆鑄件轉換成為武神的祝福書",false)
add_ox_quiz(1,"祝福之珠之功能是使用後可以將物品+4至+5成功率提高為100%",false)
add_ox_quiz(1,"咒安密笈功能是物品屬性轉換秘笈＋追加物品屬性秘笈＋吸石秘笈",false)
add_ox_quiz(1,"官網相關剷除白蓮魅影等級限制 21 ?",false)
add_ox_quiz(1,"帝國戰開始後各國的子民可以點擊各國城市內的王鐵匠選擇參戰?",false)
add_ox_quiz(1,"專門負責儲存物品的NPC 是王鐵匠?",false)
add_ox_quiz(1,"販賣藥品、卷軸、包裹、鞋子和飾物等各種雜物是梁柏年?",false)
add_ox_quiz(1,"專賣各種盔甲裝備的NPC 白鰱魅影 ?",false)
add_ox_quiz(1,"同種職業加入不同門派將會學到不同的技能的NPC是戰魂",false)
add_ox_quiz(1,"幻化其中之ㄧ條件 可幻化等級最高不能超過自身等級的10級",false)
add_ox_quiz(1,"幻化條件其中之ㄧ一次變身的時間最多可以維持20分鐘 ",false)
add_ox_quiz(1,"裝備鍛造的NPC是 蓮嫂",false)
add_ox_quiz(1,"公會成員超過10人時才有資格向其他公會宣戰",false)
add_ox_quiz(1,"不只有公會會長一人才有宣戰的權力",false)
add_ox_quiz(1,"地盤戰:使用現有地圖，限制時間為10分鐘。 ",false)
add_ox_quiz(1,"霸王戰:使用專用的公會戰爭地圖，限制時間為30分鐘",false)
add_ox_quiz(1,"50級以上的玩家備10萬金幣，到戰魂那裏便可以申請創建公會",false)
add_ox_quiz(1,"公會等級每升一級可獲得200點的龍神力量。",false)
add_ox_quiz(1,"幫會基地鐵匠的鍛造成功率比普通王鐵匠高50%",false)
add_ox_quiz(1,"完成亡靈塔六層任務後會出現一名蓮嫂",false)
add_ox_quiz(1,"結婚條件:必須擁有1000萬金幣的結婚費用。 ",false)
add_ox_quiz(1,"馬匹圖示顏色變為綠色時，馬匹便告死亡",false)
add_ox_quiz(1,"得到仙草後，需要交給梁柏年復活馬匹",false)
add_ox_quiz(1,"只要玩家達等級50並習得釣魚技能",false)
add_ox_quiz(1,"魚竿及魚餌可於雜貨店購買",false)
add_ox_quiz(1,"魚竿的性能會隨著打怪的次數上升?",false)
add_ox_quiz(1,"採礦系統是利用鐮刀工具來進行採礦，以而獲得寶貴的礦石",false)
add_ox_quiz(1,"採礦步驟:首先找到副城中的魚夫，向他購買鋤頭。",false)
add_ox_quiz(1,"有無字天書可開始學習採礦?",false)
add_ox_quiz(1,"馬匹召喚出來後，螢幕的左上角會顯示馬的狀態",false)
add_ox_quiz(1,"觀看婚禮超過60分鐘的賓客還可獲得禮品?",false)
add_ox_quiz(1,"馬牌需要伯樂花費一天的時間去為你量身打造，花費為20萬金幣。 ",false)
add_ox_quiz(1,"使用不安秘笈和後人的教訓連續修練採礦技能提高修練成功率 ",false)
add_ox_quiz(1,"將原石拖到小紅身上就可以進行精煉",false)
add_ox_quiz(1," 馬匹死亡以後，可以使用草復活",false)
add_ox_quiz(1,"刺客驅使著黑暗魔法、揮舞著致命的武器?",false)
add_ox_quiz(1,"猛將技能有:連射 怒箭 輕功……等",false)
add_ox_quiz(1,"神女技能有:　旋魔 束縛 ……等",false)
add_ox_quiz(1,"精通仙術的猛將將成為戰場上至關重要的角色",false)
add_ox_quiz(1,"刺客技能有:落雷 飄仙 神曲……等",false)
add_ox_quiz(1,"產包儲值後 可和遊戲內NPC小虹領取",false)
add_ox_quiz(1,"龍駒定期維護時間 每星期四 13:00PM 至 14:00PM",false)
add_ox_quiz(1,"當魚竿的修練度到達升級值時，可以找到倉庫老人進行升級",false)
add_ox_quiz(1,"學習輔助技能幻化增加招式變化，增加攻擊次數",false)
add_ox_quiz(1,"新受寶典的功能是:提升天調國語言的理解力",false)
add_ox_quiz(1,"為保證敏捷和速度使用輕便的防禦盔甲是神女唯一的弱點",false)
add_ox_quiz(1,"學習輔助技能鍛造提升領導能力，提高組隊效率",false)
add_ox_quiz(1,"修羅技能有:光浴 飄仙…...等",false)
add_ox_quiz(1,"進勞寶典的功能是:提升新受國語言的理解力",false)
add_ox_quiz(1,"修羅是戰場上力量與尊嚴的象徵?",false)
add_ox_quiz(1,"天調寶典的功能是:提升春天國語言的理解力",false)
add_ox_quiz(1,"魚可以用煙火來製成烤魚，烤魚會按魚的種類而發揮不同的效果",false)
add_ox_quiz(1,"釣魚池分ㄧ級釣魚池、二級釣魚池及三級釣魚池三種",false)
add_ox_quiz(1,"情商指數的初始值為70%，從角色結婚的瞬間開始累計",false)
add_ox_quiz(1,"如遺失馬牌，可以到伯樂處辦理補辦手續，費用是十萬金幣。",false)
add_ox_quiz(1,"比長江還要長的河是黃河嗎？",false)
add_ox_quiz(1,"X射線的發現者是居里夫人嗎？",false)
add_ox_quiz(1,"中文歌背叛的原唱是楊宗煒?",false)
add_ox_quiz(1,"龍駒台灣伺服器是黑龍和幻魔？",false)
add_ox_quiz(1,"唐詩《登岳陽樓》的作者是李白嗎？",false)
add_ox_quiz(1,"中正紀念堂位於高雄市",false)
add_ox_quiz(1,"龍駒是付費線上遊戲?",false)
add_ox_quiz(1,"台灣水果黑珍珠是指香蕉?",false)
add_ox_quiz(1,"田壘是台灣著名的棒球選手?",false)
add_ox_quiz(1,"2007年今年2月有29天?",false)
add_ox_quiz(1,"由太空拍攝到地球景象，彎彎的淺藍色色帶是森林地帶。",false)
add_ox_quiz(1,"將塑膠袋埋在地下，可以被土質分解。",false)
add_ox_quiz(1,"汙染的空氣對動物有害，對植物並沒有影響",false)
add_ox_quiz(1,"籃球先發球員有12個",false)
add_ox_quiz(1,"中文歌紅蜻蜓是少女隊唱的?",false)
add_ox_quiz(1,"卡通小玩子的爺爺名字叫做阿宏?",false)
add_ox_quiz(1,"多啦A夢的任意門可以回到過去",false)
add_ox_quiz(1,"捷運系統內不可吸菸但可飲食",false)
add_ox_quiz(1,"所謂的三溫暖是指 泡 開水 冷水和 冰水",false)
add_ox_quiz(1,"台灣法律規定16歲未滿18歲的青少年可以觀看限制級電影",false)
add_ox_quiz(1,"林志穎主演偶像劇,劇名為放羊的咪咪嗎?",false)
add_ox_quiz(1,"浣熊是森林之王嗎?",false)
add_ox_quiz(1,"全家就是你家是7-11的廣告詞?",false)
add_ox_quiz(1,"K歌之王的原唱是陳雷",false)
add_ox_quiz(1,"台灣第一高峰是陽明山",false)
add_ox_quiz(1,"只有在太陽光下有影子，在燈光下不會有影子。",false)
add_ox_quiz(1,"孫燕姿咕嘰咕嘰請到忍者少年幫她伴舞?",false)
add_ox_quiz(1,"卡通蠟筆小新最喜歡的是鹹蛋超人?",false)
add_ox_quiz(1,"卡通名偵探柯南,毛利蘭的爸爸是花利小五郎?",false)
add_ox_quiz(1,"卡通櫻桃小丸子 班長是花輪?",false)
add_ox_quiz(1,"愛新覺羅是唐朝的姓氏?",false)
add_ox_quiz(1,"人魚公主為了變成人類把眼睛賣給了巫婆?",false)
add_ox_quiz(1,"孔子的中心思想是謙愛非攻?",false)
add_ox_quiz(1,"卡通櫻桃小丸子家裡失火頭型像洋蔥是野口?",false)
add_ox_quiz(1,"大象林旺爺爺出生在越南",false)
add_ox_quiz(1,"鹿鼎記以元朝代作為故事背景?",false)
add_ox_quiz(1,"桃花源記 是曹雪芹嚮往的大同世界?",false)
add_ox_quiz(1,"中國四大發明之一紙是蔡邕發明的?",false)
add_ox_quiz(1,"宋朝的開國皇帝是花和尚",false)
add_ox_quiz(1,"漢朝得開國皇帝是後藤新平",false)
add_ox_quiz(1,"唐朝的開國皇帝唐三藏",false)
add_ox_quiz(1,"灰姑娘的後母有7個親生女兒?",false)
add_ox_quiz(1,"中國傳奇故事開天闢地的英雄是梵谷",false)
add_ox_quiz(1,"中國傳奇故事鬼娃造人補天嗎?",false)
add_ox_quiz(1,"一飯千金呂不偉 報答老婆婆在自己飢冷交迫時 送飯菜給自己吃 ?",false)
add_ox_quiz(1,"長恨歌-詩人李商隱膾炙人口的名篇",false)
add_ox_quiz(1,"長恨歌-是描述唐玄宗和武則天 的悲劇故事?",false)
add_ox_quiz(1,"孤雛淚-是以英國商業革命時代作為故事背景",false)
add_ox_quiz(1,"白雪公主後母擁有神燈,這東西會說出世界上最美麗的女人是誰?",false)
add_ox_quiz(1,"灰姑娘故事,灰姑娘遺失了蘋果 卻讓王子找到她?",false)
add_ox_quiz(1,"清朝最後一個皇帝是溥飯?",false)
add_ox_quiz(1,"在台灣12月25日是萬聖節",false)
add_ox_quiz(1,"端午節是為了紀念荊軻?",false)
add_ox_quiz(1,"嫦娥奔月故事中,嫦娥的老公是吳剛?",false)
add_ox_quiz(1,"小紅帽故事中,把大野狼肚子剖開救出小紅帽和外婆的是 松鼠 ?",false)
add_ox_quiz(1,"台灣原住民族群中長腿族人有彰顯的黥面文化",false)
add_ox_quiz(1,"五人制室內足球賽,需要20個球員在場上?",false)
add_ox_quiz(1,"中國傳奇故事中說明中國人在過年的時候放鞭炮,是為了趕走熊?",false)
add_ox_quiz(1,"著名小說半生緣作者是瓊瑤?",false)
add_ox_quiz(1,"童話故事三隻小豬,老三的房子是用稻草做成的",false)
add_ox_quiz(1,"漢武帝為抵抗匈奴入侵,張三豐派出使西域?",false)
add_ox_quiz(1,"哭倒長城的是西施",false)
add_ox_quiz(1,"明代初年的盛事時人稱為三保太監下西洋的是小春子?",false)
add_ox_quiz(1,"台灣第一高峰是觀音山?",false)
add_ox_quiz(1,"中國人習俗遇大象發?",false)
add_ox_quiz(1,"神雕俠侶 小龍女的愛人是令狐沖?",false)
add_ox_quiz(1,"射鵰英雄傳裡冰雪聰明的女主角大名是小龍女?",false)
add_ox_quiz(1,"四聖獸 青龍白虎朱雀  還有一個是天龍?",false)
add_ox_quiz(1,"孫悟空有36變?",false)
add_ox_quiz(1,"媽祖娘娘的左右護法金童玉女?",false)
add_ox_quiz(1,"媽祖娘娘本名張三豐?",false)
add_ox_quiz(1,"青蛙小時候是蝴蝶?",false)
add_ox_quiz(1,"毛毛蟲會變成天鵝?",false)
add_ox_quiz(1,"登金陵鳳凰台 請問是李白的大作?",false)
add_ox_quiz(1,"吳哥窟位於埃及?",false)
add_ox_quiz(1,"卡通多啦A夢裡唱歌難聽愛打棒球的是老師",false)
add_ox_quiz(1,"過世的狗明星雅夫是吉娃娃",false)
add_ox_quiz(1,"孫燕姿綠光歌曲裡燕姿嘗試土風舞",false)
add_ox_quiz(1,"變形金剛裡山姆的小狗是黃金獵犬?",false)
add_ox_quiz(1,"卡通櫻桃小丸子 有錢人家的少爺是丸尾",false)
add_ox_quiz(1,"多啦A夢是30世紀的產物",false)
add_ox_quiz(1,"徐若瑄以前是少女隊的團員",false)
add_ox_quiz(1,"電影鐵達尼號女主角大名是安妮?",false)
add_ox_quiz(1,"小飛俠彼得潘裡和他們做對的船長大名杰克船長?",false)
add_ox_quiz(1,"蔡依林是泰國大學西班牙文學系畢業的學生?",false)
add_ox_quiz(1,"梁山伯 最愛是貂蟬?",false)
add_ox_quiz(1,"環珠格格的好姐妹是西藏喇嗎?",false)
add_ox_quiz(1,"茱麗葉的男朋友是圓桌武士",false)
add_ox_quiz(1,"偶像劇流星花園男主角是 永澤",false)
add_ox_quiz(1,"韓國偶像劇藍色生死戀 女主角是 安潔莉娜裘莉",false)
add_ox_quiz(1,"颱風是源自熱帶海洋上的強烈高氣壓,暴風半徑可達數百公里",false)
add_ox_quiz(1,"葉綠素是靠海水製造",false)
add_ox_quiz(1,"朱自清-背影 在描述 母子之間的情感",false)
add_ox_quiz(1,"被皇后趕出門之後收留白雪公主的是3隻小豬",false)
add_ox_quiz(1,"在射手座之後的星座是魔羯座",false)
add_ox_quiz(1,"小木偶最後沒有變成人類",false)
add_ox_quiz(1,"說謊的小木偶 手腳會變長",false)
add_ox_quiz(1,"偶像劇換換愛的女主角是楊丞林",true)
add_ox_quiz(1,"中央氣象局以颱風中心平均最大風速將之分為輕度、中度、強烈颱風",true)
add_ox_quiz(1,"龍捲風在溫暖濕潤的空氣和寒冷乾燥的空氣相遇的鋒面上而形成的",true)
add_ox_quiz(1,"十九世紀下，柴可夫斯基透過天鵝湖 睡美人 胡桃鉗實現了舞劇音樂的革新",true)
add_ox_quiz(1,"白雪公主的名字是因為出生時皮膚像雪ㄧ樣白",true)
add_ox_quiz(1,"三分線後方投重的球叫做三分球",true)
add_ox_quiz(1,"商鞅，姓公孫，名鞅。號為商君，所以又稱為商鞅",true)
add_ox_quiz(1,"罄竹難書-在說形容罪行多得寫不完。",true)
add_ox_quiz(1,"一字千金凡是指一篇文章寫的非常出色，價值很高，都可用這句成語來形容。 ",true)
add_ox_quiz(1,"小時了了 是只人在幼年時聰敏捷，表現優良，長大之後未必能有所成就。",true)
add_ox_quiz(1,"瓜田李下是只比喻容易讓人引起懷疑的舉動等",true)
add_ox_quiz(1,"士別三日 比喻 進步神速，使人另眼相看。",true)
add_ox_quiz(1,"ㄧ日三秋是只說一天不見面，就好像隔了三年一樣。形容思念殷切",true)
add_ox_quiz(1,"三人成虎比喻形容謠傳的人一多，就能使人認假為真",true)
add_ox_quiz(1,"李後主:初名從嘉，即位後，更名煜，字重光",true)
add_ox_quiz(1,"紅樓夢全書一百二十回?",true)
add_ox_quiz(1,"李清照是南北宋之交著名的女詞人，號易安居士",true)
add_ox_quiz(1,"灌籃是得2分",true)
add_ox_quiz(1,"喔 喔喔喔….你是我的花朵你是我的花朵 是伍佰老師的歌",true)
add_ox_quiz(1,"井底之蛙 是比喻 見識淺薄，不知天高地厚的人",true)
add_ox_quiz(1,"徙木立信-是在說商鞅的故事",true)
add_ox_quiz(1,"中國近代文學駱駝祥子是老舍的作品",true)
add_ox_quiz(1,"偶像劇:我的秘密花園最喜歡范曉敏的是黃耀輝",true)
add_ox_quiz(1,"人生自古誰無死 留取丹心照汗青 是文天祥的名句?",true)
add_ox_quiz(1,"中國第一個女皇帝是武則天?",true)
add_ox_quiz(1,"天龍八部是金庸寫的小說?",true)
add_ox_quiz(1,"雲起代理的遊戲帳號申請流程是先開通雲起會員帳號後再開啟遊戲帳號?",true)
add_ox_quiz(1,"雲遊卡點數必須先分配到遊戲帳號底下後才能夠在遊戲商城購物?",true)
add_ox_quiz(1,"飛魚季是泰雅族人的活動,國曆三月份開始，至國曆九月上旬為止",true)
add_ox_quiz(1,"台灣雲起客服專線是24小時",true)
add_ox_quiz(1,"統一獅隊明星外野手「甘蔗」是黃甘霖",true)
add_ox_quiz(1,"棒球正式比賽應賽完九局",true)
add_ox_quiz(1,"森林被過度砍伐後，水土不易保持，造成土壤流失。",true)
add_ox_quiz(1,"台灣人民享有信仰宗教的自由",true)
add_ox_quiz(1,"中元普渡儀式源自於目連救母故事",true)
add_ox_quiz(1,"著名百老匯歌舞劇歌劇魅影是作曲家安德魯韋伯的作品",true)
add_ox_quiz(1,"卡通名偵探柯南,柯南的真實身份是高中生工藤新一",true)
add_ox_quiz(1,"卡通蠟筆小新的妹妹是小葵",true)
add_ox_quiz(1,"管理交通的警察叫作交通警察",true)
add_ox_quiz(1,"大象林旺出生於緬甸",true)
add_ox_quiz(1,"不吃豬肉的是回教徒",true)
add_ox_quiz(1,"港星劉德華的英文名字是ANDY",true)
add_ox_quiz(1,"中國近代文學阿Q正傳作者是魯迅 ",true)
add_ox_quiz(1,"豹屬於貓科",true)
add_ox_quiz(1,"舞孃主唱是蔡依林",true)
add_ox_quiz(1,"高雄目前最大的shop mall是夢世界",true)
add_ox_quiz(1,"中國人放鞭炮習俗是源自要嚇跑年獸",true)
add_ox_quiz(1,"引起地球溫室效應的主因是過多的CO2",true)
add_ox_quiz(1,"三原色是指紅綠藍",true)
add_ox_quiz(1,"中國人吃湯圓的習俗代表團圓",true)
add_ox_quiz(1,"第一任台灣巡撫劉銘傳",true)
add_ox_quiz(1,"貓用腳掌散熱",true)
add_ox_quiz(1,"造成溫室效應的主要原因是二氧化碳",true)
add_ox_quiz(1,"中國四大章回小說三國演義 水滸傳 西遊記 紅樓夢",true)
add_ox_quiz(1,"貝克漢是足球員",true)
add_ox_quiz(1,"影印的原稿顏色太濃時，影像濃度設定要調淡些。",true)
add_ox_quiz(1,"[ 人非聖賢，誰能無過 ]，就是要我們勇於認錯。",true)
add_ox_quiz(1,"1/1是元旦",true)
add_ox_quiz(1,"跑步的時候，影子也會跟著移動",true)
add_ox_quiz(1,"鈣是製造骨骼及牙 齒 的 原 料 ",true)
add_ox_quiz(1,"電影鐵達尼號女主角大名蘿絲(ROSE)?",true)
add_ox_quiz(1,"小飛俠彼得潘裡和他們做對的船長大名虎克(船長)?",true)
add_ox_quiz(1," 以一曲姐妹大紅的女歌手是張惠妹?",true)
add_ox_quiz(1,"日本節目黃金傳說喜歡捕魚過省錢生活 的好孩子大名是濱口優?",true)
add_ox_quiz(1,"卡通櫻桃小丸子 小玉的爸爸最喜歡幫大家拍照?",true)
add_ox_quiz(1,"卡通遊戲王主角,黑魔導的主人是武藤遊戲?",true)
add_ox_quiz(1,"動感超人發功 … 請問動感超人的武功名稱是動感光波嗎?",true)
add_ox_quiz(1,"MR.Q蔡依林MV男主角是陳冠希?",true)
add_ox_quiz(1,"多啦A夢最喜歡的點心是銅鑼燒?",true)
add_ox_quiz(1,"生存力繁殖力適應力都超強的小強本名是蟑螂?",true)
add_ox_quiz(1,"韓劇浪漫滿屋女主角在戲中的大名是韓智恩?",true)
add_ox_quiz(1,"時下流行的嘻哈(HIP HOP)文化 是美國黑人的地下文化其目地在於紓發情緒?",true)
add_ox_quiz(1,"老子提倡 無為而治的 ?",true)
add_ox_quiz(1,"卡通櫻桃小丸子 暗戀花輪的是美環?",true)
add_ox_quiz(1,"耶穌基督的母親大名是(聖母)瑪利亞",true)
add_ox_quiz(1," 西元前331年,勇氣征戰,為馬其頓帝國寫下最輝煌燦爛的一頁,是亞歷山大",true)
add_ox_quiz(1,"「孤雛淚」是大文豪狄更斯的作品?",true)
add_ox_quiz(1,"歷史故事三國演義主題是在說魏蜀吳三國?",true)
add_ox_quiz(1,"中國近代文學阿Q正傳作者是魯迅 ",true)
add_ox_quiz(1,"卡通名偵探柯南,柯南的真實姓名是工藤新一?",true)
add_ox_quiz(1,"棒球正式比賽應賽完是9局?",true)
add_ox_quiz(1,"多啦A夢最怕老鼠？",true)
add_ox_quiz(1,"居禮夫人發現了鐳?",true)
add_ox_quiz(1,"籃球先發球員有5個?",true)
add_ox_quiz(1,"電影哈利波特鳳凰會的密令裡,死掉的是天狼星?",true)
add_ox_quiz(1,"愚人節是4/1",true)
add_ox_quiz(1,"中文歌舞孃主唱是蔡依林?",true)
add_ox_quiz(1,"電影斷臂山導演是李安?",true)
add_ox_quiz(1,"卡通蠟筆小新的妹妹大名是小葵?",true)
add_ox_quiz(1,"變 型金剛裡山姆的守護者是大黃蜂?",true)
add_ox_quiz(1,"楊宗緯一曲背叛成名,背叛的原唱者是曹格?",true)
add_ox_quiz(1,"成語臥薪嚐膽是說句踐的故事?",true)
add_ox_quiz(1,"麻將的玩法可分成13張和16張,16張玩法在台灣比較流行?",true)
add_ox_quiz(1,"古典英文老歌Yesterday Once More是木匠兄妹唱的? ",true)
add_ox_quiz(1,"冬天過了以後是春天?",true)
add_ox_quiz(1,"天秤座後面的星座是天蠍座?",true)
add_ox_quiz(1,"王建明是美國大聯盟哪洋基隊的球員?",true)
add_ox_quiz(1,"經典名曲對你愛不完是誰香港歌手郭富城演唱的?",true)
add_ox_quiz(1,"多啦A夢 的時光機可以回到過去也可到達未來?",true)
add_ox_quiz(1,"多啦A夢的竹蜻蜓可以在天空中任意飛?",true)
add_ox_quiz(1,"多啦A夢 的道具任意門可以到任何地方?",true)
add_ox_quiz(1,"扶不起的阿斗在描述劉禪?",true)
add_ox_quiz(1,"既生瑜何生亮  在說周瑜和諸葛亮？",true)
add_ox_quiz(1,"雜貨店老闆的老爸是防具店老闆嗎？",true)
add_ox_quiz(1,"蓮嫂的老公是書蟲嗎？",true)
add_ox_quiz(1,"梁柏年的老師是老學究嗎？",true)
add_ox_quiz(1,"好久沒購物了,手癢癢啦.是白蓮射手的臺詞嗎？",true)
add_ox_quiz(1,"有本事和我單挑~.是五狼兵的臺詞嗎？",true)
add_ox_quiz(1,"想不想跟我決鬥?是五狼鬼爪的臺詞嗎？",true)
add_ox_quiz(1,"無名土石碑是無名石碑之一嗎？",true)
add_ox_quiz(1,"任務《梁柏年的研究》之幫助梁柏年收集靈芝, 收集10個嗎？",true)
add_ox_quiz(1,"幫梁柏年收集的桔梗是消滅饑餓青狼首領後獲得嗎？",true)
add_ox_quiz(1,"組隊經驗分配的模式只有隊長可以設定嗎？",true)
add_ox_quiz(1,"傳送點在地圖上的標識是淡藍色四方形嗎？",true)
add_ox_quiz(1,"增加人物屬性中的敏捷會增加物理攻擊力和回避率。",true)
add_ox_quiz(1,"38以上武器可以鑲嵌3個寶石。",true)
add_ox_quiz(1,"32級以裝備可以鑲嵌3個寶石。",true)
add_ox_quiz(1,"18-37級武器可以鑲嵌2個寶石。",true)
add_ox_quiz(1,"18-31裝備可以鑲嵌2個寶石。",true)
add_ox_quiz(1,"3階技能達到4階技能是使用魂石。",true)
add_ox_quiz(1,"打開全體攻擊模式時就可以隨意PK其他玩家。",true)
add_ox_quiz(1,"與其他國人對話看到的是亂碼,是沒有學習語言書嗎？",true)
add_ox_quiz(1,"我聽見秘宗教歌了……是秘宗教主的臺詞嗎?",true)
add_ox_quiz(1,"滑鼠右鍵點擊玩家名字,選擇好友選項就能添加好友,對嗎?",true)
add_ox_quiz(1,"每種角色可以選擇在兩個門派中任選其一加入。",true)
add_ox_quiz(1,"按下Ctrl＋1～9,人物的頭頂會出現不同的趣味圖示。",true)
add_ox_quiz(1,"龍駒online中裝備加到6以上就可以發光。",true)
add_ox_quiz(1,"目前版本自由世界中每種武器最多附加5種屬性。",true)
add_ox_quiz(1,"遊戲的窗戶和全屏模式選擇檔是config檔嗎？",true)
add_ox_quiz(1,"將物品直接托拽到對方身上可以進行交易。",true)
add_ox_quiz(1,"一刀一個成全你們.是黑風斬頭目的臺詞嗎?",true)
add_ox_quiz(1,"我期待著世界末日的到來是五狼兵怪的臺詞嗎?",true)
add_ox_quiz(1,"任務收集藥材中消滅饑餓青狼後獲得的是狼的肝臟嗎？",true)
add_ox_quiz(1,"消滅奸細任務中間諜頭目是指白蓮域首嗎？",true)
add_ox_quiz(1,"遊戲中可領取任務的NPC頭上都有箭頭提示，對嗎?",true)
add_ox_quiz(1,"快捷鍵N可查看現在所有的任務，對嗎？",true)
add_ox_quiz(1,"按〈Shift〉鍵和〈M〉鍵能控制小型地圖的開關，對嗎？",true)
add_ox_quiz(1,"佩戴熱情的面具後才可以使用表情動作嗎？",true)
add_ox_quiz(1,"消滅80個五狼兵是25級等級任務之一嗎？",true)
add_ox_quiz(1,"國戰的地圖是三岔口嗎？",true)
add_ox_quiz(1,"結婚時雙方都必須帶上定情信物，穿上禮服或婚紗嗎？",true)
add_ox_quiz(1,"購買幫會基地是找土地管理員嗎？",true)
add_ox_quiz(1,"炭金、水晶、漆石、琥珀、都鑲嵌到武器上嗎？",true)
add_ox_quiz(1,"天藍石、紫鴉石、孔雀石、月光石、都可鑲嵌到盔甲上嗎？",true)
add_ox_quiz(1,"(02)82269750是龍駒online客服專線嗎？",true)
add_ox_quiz(1,"info@runup.com.tw 是龍駒online的電子服務信箱嗎?",true)
add_ox_quiz(1,"http://mt2.runup.com.tw/是龍駒online的官方網站嗎？",true)
add_ox_quiz(1,"遊戲中的NPC老海盜已經金盆洗手了，對嗎？",true)
add_ox_quiz(1,"任務找回圓圓的年糕中，消滅的怪物是沙漠裏的真蜘蛛嗎?",true)
add_ox_quiz(1,"會國家的藥水製作術的是NPC樂師嗎？",true)
add_ox_quiz(1,"騎馬的任務是從NPC伯樂處領嗎？",true)
add_ox_quiz(1,"獅吼隕石是35級的隕石嗎？",true)
add_ox_quiz(1,"物品先人的教訓的作用是提高讀書修練成功率嗎？",true)
add_ox_quiz(1,"製作1瓶桔梗液需要1個桔梗嗎？",true)
add_ox_quiz(1,"桃花液的作用是：移動速度＋15 嗎？",true)
add_ox_quiz(1,"NPC玲兒的弟弟是小宏嗎？",true)
add_ox_quiz(1,"任務<送戰爭物資>需要消滅的怪物是【邪惡雙首蛇】嗎？",true)
add_ox_quiz(1,"任務<老海盜的藥>中需要的道具是邪惡僵屍菌嗎？",true)
add_ox_quiz(1,"任務解析疑問情報，消息是預計不久的將來有襲擊嗎?",true)
add_ox_quiz(1,"任務：回到戰魂位置 是1級的任務嗎？",true)
add_ox_quiz(1,"遊戲中，夫妻雙方感情破裂後可以離婚對嗎？",true)
add_ox_quiz(1,"遊戲中，結婚的地圖是愛情島嗎？",true)
add_ox_quiz(1,"遊戲中創建幫會的人物等級需要達到30級嗎？",true)
add_ox_quiz(1,"幫會等級越高可以使用的幫會技能越多，對嗎？",true)
add_ox_quiz(1,"26級人物可以騎乘幼年馬，對嗎？",true)
add_ox_quiz(1,"馬匹體力耗盡死亡時，使用仙草可以復活，對嗎？",true)
add_ox_quiz(1,"遊戲中用於採礦的工具是鎬鋤頭嗎？",true)
add_ox_quiz(1,"遊戲中可採到原礦有：白金、銅、銀、水晶等，對嗎？",true)
add_ox_quiz(1,"玩家常說的黃國是指天調國嗎？",true)
add_ox_quiz(1,"玩家常說的紅國是新受國嗎？",true)
add_ox_quiz(1,"玩家常說的藍國是指進勞國嗎？",true)
add_ox_quiz(1,"釣魚得到的珍珠和採礦得到的珍珠功能一樣，對嗎？",true)
add_ox_quiz(1,"孔雀石、日光石、紫鴉石都可以鑲嵌在盔甲上，對嗎？",true)
add_ox_quiz(1,"水晶、翡翠、黃銅都可以鑲嵌在武器上，對嗎？",true)
add_ox_quiz(1,"增加人物屬性中的體力可以提高生命和防禦力，對嗎？",true)
add_ox_quiz(1,"龍駒online台灣地區代理商是雲起遊戲代理有限公司(台灣) 嗎？",true)
add_ox_quiz(1,"新受國的縣城是資楊縣，對嗎？",true)
add_ox_quiz(1,"舒寒山、影悲沙漠、昇龍谷均為中立地圖嗎？",true)
add_ox_quiz(1,"刺客可學習的技能暗襲、隱擊、毒霧均為鋒刀門的嗎？",true)
add_ox_quiz(1,"神女可以學習的技能結界是潛龍門的嗎？",true)
add_ox_quiz(1,"神女可以學習的技能神曲是狂雷門的嗎？",true)
add_ox_quiz(1,"刺客可以學習的技能隱身是鋒刀門的嗎？",true)
add_ox_quiz(1,"刺客可以學習的技能魅影是鋒刀門的嗎？",true)
add_ox_quiz(1,"刺客可以學習的技能亂箭是鋒刀門的嗎？",true)
add_ox_quiz(1,"刺客可以學習的技能亂箭是百羿門的嗎？",true)
add_ox_quiz(1,"刺客可以學習的技能毒箭是百羿門的嗎？",true)
add_ox_quiz(1,"修羅可以學習的技能黑魔咒、黑龍咒均為黑魔門的嗎？",true)
add_ox_quiz(1,"修羅可以加入的門派是幻舞和黑魔嗎？",true)
add_ox_quiz(1,"《龍駒Online》是一款以戰鬥為核心的網路遊戲",true)
add_ox_quiz(1,"禮坤豪驅策著軍隊，征服大陸，第一個統一大陸。",true)
add_ox_quiz(1,"修羅為了得到無上法力，把惡魔的種子寄生在自己的手臂上",true)
add_ox_quiz(1,"刺客是以短劍和弓箭為主的專業殺手。",true)
add_ox_quiz(1,"組建幫會的NPC是戰魂?",true)
add_ox_quiz(1,"使用怪物爆出的百變盔甲後可進行變身",true)
add_ox_quiz(1,"滑鼠左鍵點擊物品欄中需升級的裝備，拖放到王鐵匠身上可進行裝備鍛造",true)
add_ox_quiz(1,"組隊是使玩家在和其他玩家一同打怪時更多樣化、更有效果的系統",true)
add_ox_quiz(1,"組隊成員間的等級差不能大於15",true)
add_ox_quiz(1,"一個隊伍的最大成員數為8，人數越多，系統獎勵的經驗就越高",true)
add_ox_quiz(1,"對一個隊伍的隊長來說，學習統帥的技能非常必要",true)
add_ox_quiz(1,"公會會長可以使用技能對全體公會成員都有效",true)
add_ox_quiz(1,"公會的將軍可以騎乘各種聖獸",true)
add_ox_quiz(1,"地皮的價格取決於地皮距村莊的距離及地皮本身的景致",true)
add_ox_quiz(1,"專用地圖名稱：新受國-中浪縣、進勞國-林河縣、天調國-臥龍縣",true)
add_ox_quiz(1,"基地專用地圖上分佈著一些怪物，適合25～35級的玩家練功",true)
add_ox_quiz(1,"地皮價格範圍：4～7千萬金幣",true)
add_ox_quiz(1,"建築了力量祭壇後，公會的等級會提升一級",true)
add_ox_quiz(1,"熔爐是用來精煉在採礦中所發掘到的礦石之用",true)
add_ox_quiz(1,"在幫會基地以及亡靈塔等地點追加超級鐵匠提升物品鍛造的成功率",true)
add_ox_quiz(1,"幫會基地的鐵匠有三種，分別負責鍛造武器、裝備和首飾",true)
add_ox_quiz(1,"幫派可購買土地，發展幫派基地，建立獨有的幫派標誌和建築",true)
add_ox_quiz(1,"土地已售出，小地圖內便會顯示購買了空地的公會名稱。 ",true)
add_ox_quiz(1,"在建造幫會基地，樹立幫會威信和榮譽之前，首先需要購買一塊地皮",true)
add_ox_quiz(1,"在幫派建築中，總共有12種熔爐可供建造?",true)
add_ox_quiz(1,"結婚條件:角色等級都到達35級以上，且兩人等級差距不高於15級",true)
add_ox_quiz(1,"婚之前必先要準備定情信物和禮服",true)
add_ox_quiz(1,"情商指數在遊戲中代表夫妻之間感情的深淺程度",true)
add_ox_quiz(1,"馬匹分為幼馬，成年馬和良駒三個階段",true)
add_ox_quiz(1,"男女角色的情商指數的數值會每天自動增加",true)
add_ox_quiz(1,"幫派基地建設系統是《龍駒》的主要特色和賣點之一",true)
add_ox_quiz(1,"雙方都符合結婚條件交足結婚費用系統將自動傳送至婚禮殿堂愛情島。",true)
add_ox_quiz(1,"殺死下仙洞中的獼猴，將會獲得任務道具神駿魂；",true)
add_ox_quiz(1,"使用馬牌可召喚出馬，召喚時有一定失敗幾率，",true)
add_ox_quiz(1,"馬匹分為幼馬，成年馬和良駒三個階段",true)
add_ox_quiz(1,"仙草分別從移山大聖、通風大聖、齊天大聖身上打落?",true)
add_ox_quiz(1,"情商指數會直接影響情侶物品的性能",true)
add_ox_quiz(1,"申請結婚男女角色身上必須擁有結婚信物和禮服?",true)
add_ox_quiz(1,"幫會等級必須達到10級以上同時花費一定數量的金幣才能購買。",true)
add_ox_quiz(1,"力量祭壇可以進行三階段的升級?",true)
add_ox_quiz(1,"幫會基地專用地圖上有18處地皮供幫會購買",true)
add_ox_quiz(1,"公會會長可以在公會內部設定15個職位，並賦予每個職位相應的許可權",true)
add_ox_quiz(1,"公會會長在公會視窗點擊龍神力量來恢復它,每恢復一點需要100金幣",true)
add_ox_quiz(1,"使用公會技能時需要耗費龍神力量",true)
add_ox_quiz(1,"顛覆戰:使用專用的幫戰地圖，沒有時間限制。",true)
add_ox_quiz(1,"公會等級提升後，成員數目上限也隨之提升?",true)
add_ox_quiz(1,"要參加帝國戰,必須和地牢守衛對話",true)
add_ox_quiz(1,"官網相關問題-剷除白蓮青塵 等級限制 25級? ",true)
add_ox_quiz(1,"刺客是以短劍和弓箭為主的專業殺手。",true)
add_ox_quiz(1,"神女是領悟到自然流逝與陰陽造化的美麗化身、是凡世之賢者。",true)
add_ox_quiz(1,"猛將是戰鬥的專家?",true)
add_ox_quiz(1,"歷史學家認定在惡運石出現之後的時代為惡運時代。",true)
add_ox_quiz(1,"人們都覺得這些隕石會給大家帶來惡運，將這些隕石稱為惡運石。",true)
add_ox_quiz(1,"每次使用秘笈成功時會添加1個隨機屬性。",true)
add_ox_quiz(1,"通行證明牌之功能是穿越盤絲洞二樓的物品，進出通道會消耗",true)

